(define (pi a b c)  (if (> n 0) (= n 10) (= n 1)))
(define (pi)  (if (> n 0) (= n 10) (= n 1)))
(car '(abc def ghi))
(cdr '(abc def ghi))
(cons 'abd '(1 2 3))
(cons 'a 'b)
(cons (car '(a b c d)) (cddr '(a b c d)))
(cons (cadr '(a b c d)) (caddr '(a b c d)))
(+ 4 5 2 7 5 2)
