(define (pi a b c)  (if (> a 0) (= b 10) (= c 1)))
(define (pi)  (if (> 5 0) (= 5 10) (< 3 1)))
(car '(abc def ghi))
(cdr '(abc def ghi))
(cons 'abd '(1 2 3))
(cons 'a 'b)
(cons (car '(a b c d)) (cddr '(a b c d)))
(cons (cadr '(a b c d)) (caddr '(a b c d)))
(+ 4 5 2 7 5 2)
